# Generated by Django 3.1.4 on 2020-12-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmarkintegration',
            name='to_emails',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
